<?php

use App\Http\Controllers\Admin\AuthController as AdminAuthController;
use App\Http\Controllers\Admin\DashboardController;
use App\Http\Controllers\Admin\AboutController;
use App\Http\Controllers\Admin\ServiceController;
use App\Http\Controllers\Admin\ContactController;
use App\Http\Controllers\Admin\BlogPostController;
use App\Http\Controllers\Admin\PriceController;
use App\Http\Controllers\Admin\GalleryController;
use App\Http\Controllers\Admin\NewsEventController;
use App\Http\Controllers\Admin\TeamMemberController;
use App\Http\Controllers\Admin\VideoController;
use App\Http\Controllers\Admin\UserController;
use App\Http\Controllers\Admin\RoleController;
use App\Http\Controllers\Admin\PermissionController;
use App\Http\Controllers\Admin\UserGroupController;
use App\Http\Controllers\Admin\QuoteRequestController;
use App\Http\Controllers\Admin\QuotationController;
use App\Http\Controllers\Admin\EnquiryController;
use App\Http\Controllers\Admin\NewsletterSubscriberController;
use App\Http\Controllers\Admin\CategoryController;
use App\Http\Controllers\Admin\ProductController;
use App\Http\Controllers\Admin\OrderController;
use App\Http\Controllers\Admin\CouponController;
use App\Http\Controllers\Admin\ProductReviewController as AdminProductReviewController;
use App\Http\Controllers\Admin\ReportController;
use App\Http\Controllers\Admin\ProductQuestionController as AdminProductQuestionController;
use App\Http\Controllers\Admin\VendorController;
use App\Http\Controllers\Admin\VendorPayoutController;
use App\Http\Controllers\Frontend\HomeController;
use App\Http\Controllers\Frontend\QuoteController;
use App\Http\Controllers\Frontend\BlogController;
use App\Http\Controllers\Frontend\AuthController;
use App\Http\Controllers\Frontend\ShopController;
use App\Http\Controllers\Frontend\CartController;
use App\Http\Controllers\Frontend\OrderTrackingController;
use App\Http\Controllers\Frontend\AccountOrderController;
use App\Http\Controllers\Frontend\WishlistController;
use App\Http\Controllers\Frontend\ProductReviewController;
use App\Http\Controllers\Frontend\ProductQuestionController;
use App\Http\Controllers\Frontend\PaymentController;
use Illuminate\Support\Facades\Route;

Route::middleware(['web'])->group(function () {
    Route::get('/', [HomeController::class, 'index'])->name('home');
    Route::get('/shop', [ShopController::class, 'index'])->name('shop.index');
    Route::get('/shop/{product}', [ShopController::class, 'show'])->name('shop.show');
    Route::get('/cart', [CartController::class, 'index'])->name('cart.index');
    Route::post('/cart/add/{product}', [CartController::class, 'add'])->name('cart.add');
    Route::post('/cart/update/{product}', [CartController::class, 'update'])->name('cart.update');
    Route::post('/cart/remove/{product}', [CartController::class, 'remove'])->name('cart.remove');
    Route::post('/cart/clear', [CartController::class, 'clear'])->name('cart.clear');
    Route::post('/cart/coupon', [CartController::class, 'applyCoupon'])->name('cart.coupon.apply');
    Route::post('/cart/coupon/remove', [CartController::class, 'removeCoupon'])->name('cart.coupon.remove');
    Route::get('/checkout', [CartController::class, 'checkout'])->name('checkout.index');
    Route::post('/checkout', [CartController::class, 'placeOrder'])->name('checkout.place');
    Route::get('/checkout/success/{order}', [CartController::class, 'success'])->name('checkout.success');
    Route::get('/track-order', [OrderTrackingController::class, 'index'])->name('orders.track');
    Route::post('/track-order', [OrderTrackingController::class, 'search'])->name('orders.track.search');
    Route::get('/my-orders', [AccountOrderController::class, 'index'])->middleware('auth')->name('orders.my');
    Route::get('/my-orders/{order}', [AccountOrderController::class, 'show'])->middleware('auth')->name('orders.my.show');
    Route::post('/my-orders/{order}/cancel-request', [AccountOrderController::class, 'requestCancel'])->middleware('auth')->name('orders.my.cancel-request');
    Route::get('/wishlist', [WishlistController::class, 'index'])->middleware('auth')->name('wishlist.index');
    Route::post('/wishlist/{product}', [WishlistController::class, 'store'])->middleware('auth')->name('wishlist.store');
    Route::delete('/wishlist/{product}', [WishlistController::class, 'destroy'])->middleware('auth')->name('wishlist.destroy');
    Route::post('/shop/{product}/reviews', [ProductReviewController::class, 'store'])->middleware('auth')->name('shop.reviews.store');
    Route::post('/shop/{product}/questions', [ProductQuestionController::class, 'store'])->middleware('auth')->name('shop.questions.store');
    Route::post('/payments/callback', [PaymentController::class, 'callback'])->name('payments.callback');
    Route::get('/payments/return', [PaymentController::class, 'return'])->name('payments.return');
    Route::get('/blog', [BlogController::class, 'index'])->name('blog.index');
    Route::get('/blog/{slug}', [BlogController::class, 'show'])->name('blog.show');
    Route::post('/blog/{slug}/comments', [BlogController::class, 'comment'])->name('blog.comment');
    Route::post('/contact', [HomeController::class, 'contact'])->name('contact.submit');
    Route::post('/newsletter-subscribe', [HomeController::class, 'subscribeNewsletter'])->name('newsletter.subscribe');
    Route::post('/quote', [QuoteController::class, 'store'])->name('quote.store');

    // User Authentication Routes
    Route::get('/register', [AuthController::class, 'showRegister'])->middleware('guest')->name('register');
    Route::post('/register', [AuthController::class, 'register'])->middleware('guest')->name('register.submit');
    Route::get('/login', [AuthController::class, 'showLogin'])->middleware('guest')->name('login');
    Route::post('/login', [AuthController::class, 'login'])->middleware('guest')->name('login.submit');
    Route::post('/logout', [AuthController::class, 'logout'])->middleware('auth')->name('logout');

    Route::get('/admin/login', [AdminAuthController::class, 'showLogin'])->name('admin.login');
    Route::post('/admin/login', [AdminAuthController::class, 'login'])->name('admin.login.post');
    Route::post('/admin/logout', [AdminAuthController::class, 'logout'])->name('admin.logout');

    Route::prefix('admin')->name('admin.')->middleware(App\Http\Middleware\AdminMiddleware::class)->group(function () {
        Route::get('/', [DashboardController::class, 'index'])->name('dashboard');
        Route::post('/settings', [DashboardController::class, 'update'])->name('settings.update');
        Route::resource('about', AboutController::class)->names('about');
        Route::resource('services', ServiceController::class)->names('service');
        Route::resource('contacts', ContactController::class)->names('contact');
        Route::resource('enquiries', EnquiryController::class)->only(['index', 'show', 'destroy'])->names('enquiries');
        Route::resource('newsletter-subscribers', NewsletterSubscriberController::class)->only(['index', 'destroy'])->names('newsletter-subscribers');
        Route::resource('categories', CategoryController::class)->except(['show'])->names('categories');
        Route::resource('vendors', VendorController::class)->except(['show'])->names('vendors');
        Route::get('vendor-payouts', [VendorPayoutController::class, 'index'])->name('vendor-payouts.index');
        Route::post('vendor-payouts', [VendorPayoutController::class, 'store'])->name('vendor-payouts.store');
        Route::get('vendor-payouts/{vendorPayout}', [VendorPayoutController::class, 'show'])->name('vendor-payouts.show');
        Route::post('vendor-payouts/{vendorPayout}/mark-paid', [VendorPayoutController::class, 'markPaid'])->name('vendor-payouts.mark-paid');
        Route::get('vendor-payouts/export/csv', [VendorPayoutController::class, 'exportCsv'])->name('vendor-payouts.export.csv');
        Route::resource('products', ProductController::class)->except(['show'])->names('products');
        Route::post('products/bulk-update', [ProductController::class, 'bulkUpdate'])->name('products.bulk-update');
        Route::get('products/export/csv', [ProductController::class, 'exportCsv'])->name('products.export.csv');
        Route::resource('coupons', CouponController::class)->except(['show'])->names('coupons');
        Route::get('reviews', [AdminProductReviewController::class, 'index'])->name('reviews.index');
        Route::patch('reviews/{review}', [AdminProductReviewController::class, 'update'])->name('reviews.update');
        Route::delete('reviews/{review}', [AdminProductReviewController::class, 'destroy'])->name('reviews.destroy');
        Route::get('questions', [AdminProductQuestionController::class, 'index'])->name('questions.index');
        Route::patch('questions/{question}', [AdminProductQuestionController::class, 'update'])->name('questions.update');
        Route::delete('questions/{question}', [AdminProductQuestionController::class, 'destroy'])->name('questions.destroy');
        Route::get('reports', [ReportController::class, 'index'])->name('reports.index');
        Route::get('reports/vendor-commissions/csv', [ReportController::class, 'exportVendorCommissionsCsv'])->name('reports.vendor-commissions.csv');
        Route::resource('orders', OrderController::class)->only(['index', 'show', 'update'])->names('orders');
        Route::post('orders/{order}/send-confirmation', [OrderController::class, 'sendConfirmation'])->name('orders.send-confirmation');
        Route::get('orders/{order}/print', [OrderController::class, 'print'])->name('orders.print');
        Route::get('orders/{order}/pdf', [OrderController::class, 'downloadPdf'])->name('orders.pdf');
        Route::post('orders/bulk-update', [OrderController::class, 'bulkUpdate'])->name('orders.bulk-update');
        Route::get('orders/export/csv', [OrderController::class, 'exportCsv'])->name('orders.export.csv');
        Route::resource('blog', BlogPostController::class)->names('blog');
        Route::resource('prices', PriceController::class)->names('price');
        Route::resource('gallery', GalleryController::class)->except(['show'])->names('gallery');
        Route::resource('news-events', NewsEventController::class)->except(['show'])->names('news-events');
        Route::resource('videos', VideoController::class)->except(['show'])->names('video');
        Route::resource('team', TeamMemberController::class)->except(['show'])->names('team');
        Route::resource('users', UserController::class)->except(['show'])->names('users');
        Route::patch('users/{user}/role', [UserController::class, 'updateRole'])->name('users.role.update');
        Route::resource('roles', RoleController::class)->except(['show'])->names('roles');
        Route::resource('permissions', PermissionController::class)->except(['show'])->names('permissions');
        Route::resource('user-groups', UserGroupController::class)->except(['show'])->names('user-groups');
        Route::resource('quotes', QuoteRequestController::class)->only(['index', 'show', 'update', 'destroy'])->names('quotes');
        Route::get('quotes/{quote}/pdf', [QuoteRequestController::class, 'downloadPdf'])->name('quotes.pdf');

        Route::resource('quotations', QuotationController::class)->except(['show'])->names('quotations');
        Route::get('quotations/{quotation}/pdf', [QuotationController::class, 'generatePDF'])->name('quotations.pdf');
        Route::post('quotations/{quotation}/send-email', [QuotationController::class, 'sendEmail'])->name('quotations.send-email');
    });
});
