<?php

use App\Http\Controllers\Admin\AuthController as AdminAuthController;
use App\Http\Controllers\Admin\DashboardController;
use App\Http\Controllers\Admin\ProfileController;
use App\Http\Controllers\Admin\AboutController;
use App\Http\Controllers\Admin\ServiceController;
use App\Http\Controllers\Admin\ContactController;
use App\Http\Controllers\Admin\BlogPostController;
use App\Http\Controllers\Admin\PriceController;
use App\Http\Controllers\Admin\GalleryController;
use App\Http\Controllers\Admin\NewsEventController;
use App\Http\Controllers\Admin\TeamMemberController;
use App\Http\Controllers\Admin\VideoController;
use App\Http\Controllers\Admin\BackupController;
use App\Http\Controllers\Admin\ReturnController;
use App\Http\Controllers\Admin\CashierShiftController;
use App\Http\Controllers\Admin\CashierHomeController;
use App\Http\Controllers\Admin\ShopCustomerController;
use App\Http\Controllers\Admin\LoyaltyController;
use App\Http\Controllers\Admin\ExpenseController;
use App\Http\Controllers\Admin\EmployeeController;
use App\Http\Controllers\Admin\AuditLogController;
use App\Http\Controllers\Admin\HeldSaleController;
use App\Http\Controllers\Admin\BrandController;
use App\Http\Controllers\Admin\SupplierController;
use App\Http\Controllers\Admin\PurchaseController;
use App\Http\Controllers\Admin\PurchaseOrderController;
use App\Http\Controllers\Admin\TrainingController;
use App\Http\Controllers\Admin\UserController;
use App\Http\Controllers\Admin\RoleController;
use App\Http\Controllers\Admin\PermissionController;
use App\Http\Controllers\Admin\UserGroupController;
use App\Http\Controllers\Admin\QuoteRequestController;
use App\Http\Controllers\Admin\QuotationController;
use App\Http\Controllers\Admin\EnquiryController;
use App\Http\Controllers\Admin\NewsletterSubscriberController;
use App\Http\Controllers\Admin\CategoryController;
use App\Http\Controllers\Admin\ProductController;
use App\Http\Controllers\Admin\StockTakeController;
use App\Http\Controllers\Admin\OrderController;
use App\Http\Controllers\Admin\PosController;
use App\Http\Controllers\Admin\CouponController;
use App\Http\Controllers\Admin\ProductReviewController as AdminProductReviewController;
use App\Http\Controllers\Admin\ReportController;
use App\Http\Controllers\Admin\ProductQuestionController as AdminProductQuestionController;
use App\Http\Controllers\Admin\VendorController;
use App\Http\Controllers\Admin\VendorPayoutController;
use App\Http\Controllers\Frontend\HomeController;
use App\Http\Controllers\Frontend\QuoteController;
use App\Http\Controllers\Frontend\BlogController;
use App\Http\Controllers\Frontend\AuthController;
use App\Http\Controllers\Frontend\ShopController;
use App\Http\Controllers\Frontend\CartController;
use App\Http\Controllers\Frontend\OrderTrackingController;
use App\Http\Controllers\Frontend\AccountOrderController;
use App\Http\Controllers\Frontend\WishlistController;
use App\Http\Controllers\Frontend\ProductReviewController;
use App\Http\Controllers\Frontend\ProductQuestionController;
use App\Http\Controllers\Frontend\PaymentController;
use App\Http\Controllers\Admin\StockOverviewController;
use App\Http\Controllers\Admin\StockLocationController;
use App\Http\Controllers\Admin\StockTransferController;
use App\Http\Controllers\Admin\StockAdjustmentController;
use App\Http\Controllers\Admin\StockMovementController;
use App\Http\Controllers\ManifestController;
use Illuminate\Support\Facades\Route;

Route::get('/manifest.webmanifest', [ManifestController::class, 'storefront'])->name('pwa.manifest');
Route::get('/admin/manifest.webmanifest', [ManifestController::class, 'admin'])->name('pwa.manifest.admin');
Route::get('/sw.js', function () {
    if (! config('pwa.enabled', true)) {
        abort(404);
    }

    return response()
        ->view('pwa.service-worker')
        ->header('Content-Type', 'application/javascript; charset=UTF-8')
        ->header('Service-Worker-Allowed', '/')
        ->header('Cache-Control', 'no-cache, no-store, must-revalidate');
})->name('pwa.service-worker');

Route::middleware(['web'])->group(function () {
    Route::get('/', [HomeController::class, 'index'])->name('home');
    Route::get('/shop', [ShopController::class, 'index'])->name('shop.index');
    Route::get('/shop/{product}', [ShopController::class, 'show'])->name('shop.show');
    Route::get('/cart', [CartController::class, 'index'])->name('cart.index');
    Route::post('/cart/add/{product}', [CartController::class, 'add'])->name('cart.add');
    Route::post('/cart/update/{lineKey}', [CartController::class, 'update'])->name('cart.update')->where('lineKey', '[A-Za-z0-9_-]+');
    Route::post('/cart/remove/{lineKey}', [CartController::class, 'remove'])->name('cart.remove')->where('lineKey', '[A-Za-z0-9_-]+');
    Route::post('/cart/clear', [CartController::class, 'clear'])->name('cart.clear');
    Route::post('/cart/coupon', [CartController::class, 'applyCoupon'])->name('cart.coupon.apply');
    Route::post('/cart/coupon/remove', [CartController::class, 'removeCoupon'])->name('cart.coupon.remove');
    Route::get('/checkout', [CartController::class, 'checkout'])->middleware('auth')->name('checkout.index');
    Route::post('/checkout', [CartController::class, 'placeOrder'])->middleware('auth')->name('checkout.place');
    Route::get('/checkout/success/{order}', [CartController::class, 'success'])->name('checkout.success');
    Route::get('/track-order', [OrderTrackingController::class, 'index'])->name('orders.track');
    Route::post('/track-order', [OrderTrackingController::class, 'search'])->name('orders.track.search');
    Route::get('/my-orders', [AccountOrderController::class, 'index'])->middleware('auth')->name('orders.my');
    Route::get('/my-orders/{order}', [AccountOrderController::class, 'show'])->middleware('auth')->name('orders.my.show');
    Route::post('/my-orders/{order}/cancel-request', [AccountOrderController::class, 'requestCancel'])->middleware('auth')->name('orders.my.cancel-request');
    Route::post('/my-orders/{order}/return-request', [AccountOrderController::class, 'requestReturn'])->middleware('auth')->name('orders.my.return-request');
    Route::get('/wishlist', [WishlistController::class, 'index'])->middleware('auth')->name('wishlist.index');
    Route::post('/wishlist/{product}', [WishlistController::class, 'store'])->middleware('auth')->name('wishlist.store');
    Route::delete('/wishlist/{product}', [WishlistController::class, 'destroy'])->middleware('auth')->name('wishlist.destroy');
    Route::post('/shop/{product}/reviews', [ProductReviewController::class, 'store'])->middleware('auth')->name('shop.reviews.store');
    Route::post('/shop/{product}/questions', [ProductQuestionController::class, 'store'])->middleware('auth')->name('shop.questions.store');
    Route::post('/payments/callback', [PaymentController::class, 'callback'])->name('payments.callback');
    Route::get('/payments/return', [PaymentController::class, 'return'])->name('payments.return');
    Route::get('/blog', [BlogController::class, 'index'])->name('blog.index');
    Route::get('/blog/{slug}', [BlogController::class, 'show'])->name('blog.show');
    Route::post('/blog/{slug}/comments', [BlogController::class, 'comment'])->name('blog.comment');
    Route::get('/contact', [HomeController::class, 'contactPage'])->name('contact');
    Route::post('/contact', [HomeController::class, 'contact'])->name('contact.submit');
    Route::post('/newsletter-subscribe', [HomeController::class, 'subscribeNewsletter'])->name('newsletter.subscribe');
    Route::post('/quote', [QuoteController::class, 'store'])->name('quote.store');

    // User Authentication Routes
    Route::get('/register', [AuthController::class, 'showRegister'])->middleware('guest')->name('register');
    Route::post('/register', [AuthController::class, 'register'])->middleware('guest')->name('register.submit');
    Route::get('/login', [AuthController::class, 'showLogin'])->middleware('guest')->name('login');
    Route::post('/login', [AuthController::class, 'login'])->middleware('guest')->name('login.submit');
    Route::post('/logout', [AuthController::class, 'logout'])->middleware('auth')->name('logout');

    Route::get('/admin/login', [AdminAuthController::class, 'showLogin'])->name('admin.login');
    Route::post('/admin/login', [AdminAuthController::class, 'login'])->name('admin.login.post');
    Route::post('/admin/logout', [AdminAuthController::class, 'logout'])->name('admin.logout');

    Route::prefix('admin')->name('admin.')->middleware(App\Http\Middleware\AdminMiddleware::class)->group(function () {
        Route::get('/', [DashboardController::class, 'index'])->name('dashboard');
        Route::get('/cashier', CashierHomeController::class)->name('cashier.home');
        Route::get('/pos', [PosController::class, 'index'])->name('pos.index');
        Route::get('/pos/scan', [PosController::class, 'scan'])->name('pos.scan');
        Route::post('/pos/add/{product}', [PosController::class, 'add'])->name('pos.add');
        Route::post('/pos/update/{lineKey}', [PosController::class, 'update'])->name('pos.update')->where('lineKey', '[A-Za-z0-9_-]+');
        Route::post('/pos/remove/{lineKey}', [PosController::class, 'remove'])->name('pos.remove')->where('lineKey', '[A-Za-z0-9_-]+');
        Route::post('/pos/clear', [PosController::class, 'clear'])->name('pos.clear');
        Route::post('/pos/coupon', [PosController::class, 'applyCoupon'])->name('pos.coupon.apply');
        Route::post('/pos/coupon/remove', [PosController::class, 'removeCoupon'])->name('pos.coupon.remove');
        Route::post('/pos/customer', [PosController::class, 'selectCustomer'])->name('pos.customer.select');
        Route::post('/pos/customer/clear', [PosController::class, 'clearCustomer'])->name('pos.customer.clear');
        Route::post('/pos/loyalty/redeem', [PosController::class, 'redeemLoyalty'])->name('pos.loyalty.redeem');
        Route::post('/pos/loyalty/redeem/clear', [PosController::class, 'clearLoyaltyRedeem'])->name('pos.loyalty.redeem.clear');
        Route::post('/pos/charge', [PosController::class, 'charge'])->name('pos.charge');
        Route::get('/pos/receipt/{order}', [PosController::class, 'receipt'])->name('pos.receipt');
        Route::get('/holds', [HeldSaleController::class, 'index'])->name('holds.index');
        Route::post('/holds', [HeldSaleController::class, 'store'])->name('holds.store');
        Route::post('/holds/{hold}/resume', [HeldSaleController::class, 'resume'])->name('holds.resume');
        Route::delete('/holds/{hold}', [HeldSaleController::class, 'destroy'])->name('holds.destroy');
        Route::get('/customers', [ShopCustomerController::class, 'index'])->name('customers.index');
        Route::post('/customers', [ShopCustomerController::class, 'store'])->name('customers.store');
        Route::get('/customers/{customer}', [ShopCustomerController::class, 'show'])->name('customers.show');
        Route::put('/customers/{customer}', [ShopCustomerController::class, 'update'])->name('customers.update');
        Route::delete('/customers/{customer}', [ShopCustomerController::class, 'destroy'])->name('customers.destroy');
        Route::post('/customers/{customer}/loyalty-card', [LoyaltyController::class, 'issueCard'])->name('customers.loyalty.issue');
        Route::post('/customers/{customer}/loyalty-adjust', [LoyaltyController::class, 'adjust'])->name('customers.loyalty.adjust');
        Route::post('/loyalty-cards/{card}/block', [LoyaltyController::class, 'blockCard'])->name('loyalty.cards.block');
        Route::get('/loyalty', [LoyaltyController::class, 'dashboard'])->name('loyalty.dashboard');
        Route::get('/loyalty/history', [LoyaltyController::class, 'history'])->name('loyalty.history');
        Route::get('/loyalty/settings', [LoyaltyController::class, 'settings'])->name('loyalty.settings');
        Route::put('/loyalty/settings', [LoyaltyController::class, 'updateSettings'])->name('loyalty.settings.update');

        Route::resource('employees', EmployeeController::class)->names('employees');
        Route::get('employees/{employee}/print-form', [EmployeeController::class, 'printForm'])->name('employees.print-form');
        Route::post('employees/{employee}/create-login', [EmployeeController::class, 'createLogin'])->name('employees.create-login');
        Route::post('employees/{employee}/reset-login', [EmployeeController::class, 'resetLogin'])->name('employees.reset-login');

        Route::get('/expenses', [ExpenseController::class, 'index'])->name('expenses.index');
        Route::post('/expenses', [ExpenseController::class, 'store'])->name('expenses.store');
        Route::delete('/expenses/{expense}', [ExpenseController::class, 'destroy'])->name('expenses.destroy');
        Route::get('/audit-logs', [AuditLogController::class, 'index'])->name('audit-logs.index');
        Route::get('/audit-logs/export', [AuditLogController::class, 'export'])->name('audit-logs.export');
        Route::post('/audit-logs/toggle', [AuditLogController::class, 'toggle'])->name('audit-logs.toggle');
        Route::delete('/audit-logs/bulk-destroy', [AuditLogController::class, 'bulkDestroy'])->name('audit-logs.bulk-destroy');
        Route::delete('/audit-logs/{auditLog}', [AuditLogController::class, 'destroy'])->name('audit-logs.destroy');
        Route::post('/audit-logs/clear', [AuditLogController::class, 'clear'])->name('audit-logs.clear');
        Route::get('/brands', [BrandController::class, 'index'])->name('brands.index');
        Route::post('/brands', [BrandController::class, 'store'])->name('brands.store');
        Route::delete('/brands/{brand}', [BrandController::class, 'destroy'])->name('brands.destroy');
        Route::get('/suppliers', [SupplierController::class, 'index'])->name('suppliers.index');
        Route::get('/suppliers/create', [SupplierController::class, 'create'])->name('suppliers.create');
        Route::post('/suppliers', [SupplierController::class, 'store'])->name('suppliers.store');
        Route::get('/suppliers/{supplier}/edit', [SupplierController::class, 'edit'])->name('suppliers.edit');
        Route::put('/suppliers/{supplier}', [SupplierController::class, 'update'])->name('suppliers.update');
        Route::delete('/suppliers/{supplier}', [SupplierController::class, 'destroy'])->name('suppliers.destroy');
        Route::get('/purchases', [PurchaseController::class, 'index'])->name('purchases.index');
        Route::get('/purchases/create', [PurchaseController::class, 'create'])->name('purchases.create');
        Route::post('/purchases', [PurchaseController::class, 'store'])->name('purchases.store');
        Route::get('/purchases/{purchase}', [PurchaseController::class, 'show'])->name('purchases.show');
        Route::post('/purchases/{purchase}/payment', [PurchaseController::class, 'payment'])->name('purchases.payment');
        Route::get('/purchase-orders', [PurchaseOrderController::class, 'index'])->name('purchase-orders.index');
        Route::get('/purchase-orders/create', [PurchaseOrderController::class, 'create'])->name('purchase-orders.create');
        Route::post('/purchase-orders', [PurchaseOrderController::class, 'store'])->name('purchase-orders.store');
        Route::get('/purchase-orders/{purchaseOrder}', [PurchaseOrderController::class, 'show'])->name('purchase-orders.show');
        Route::post('/purchase-orders/{purchaseOrder}/submit', [PurchaseOrderController::class, 'submit'])->name('purchase-orders.submit');
        Route::post('/purchase-orders/{purchaseOrder}/approve', [PurchaseOrderController::class, 'approve'])->name('purchase-orders.approve');
        Route::post('/purchase-orders/{purchaseOrder}/cancel', [PurchaseOrderController::class, 'cancel'])->name('purchase-orders.cancel');
        Route::post('/purchase-orders/{purchaseOrder}/receive', [PurchaseOrderController::class, 'receive'])->name('purchase-orders.receive');
        Route::get('/settings', [DashboardController::class, 'settings'])->name('settings.edit');
        Route::post('/settings', [DashboardController::class, 'update'])->name('settings.update');
        Route::get('/profile', [ProfileController::class, 'edit'])->name('profile.edit');
        Route::put('/profile', [ProfileController::class, 'update'])->name('profile.update');
        Route::resource('about', AboutController::class)->names('about');
        Route::resource('services', ServiceController::class)->names('service');
        Route::resource('contacts', ContactController::class)->names('contact');
        Route::resource('enquiries', EnquiryController::class)->only(['index', 'show', 'destroy'])->names('enquiries');
        Route::resource('newsletter-subscribers', NewsletterSubscriberController::class)->only(['index', 'destroy'])->names('newsletter-subscribers');
        Route::resource('categories', CategoryController::class)->except(['show'])->names('categories');
        Route::resource('vendors', VendorController::class)->except(['show'])->names('vendors');
        Route::get('vendor-payouts', [VendorPayoutController::class, 'index'])->name('vendor-payouts.index');
        Route::post('vendor-payouts', [VendorPayoutController::class, 'store'])->name('vendor-payouts.store');
        Route::get('vendor-payouts/{vendorPayout}', [VendorPayoutController::class, 'show'])->name('vendor-payouts.show');
        Route::post('vendor-payouts/{vendorPayout}/mark-paid', [VendorPayoutController::class, 'markPaid'])->name('vendor-payouts.mark-paid');
        Route::get('vendor-payouts/export/csv', [VendorPayoutController::class, 'exportCsv'])->name('vendor-payouts.export.csv');
        Route::get('products/generate-sku', [ProductController::class, 'generateSku'])->name('products.generate-sku');
        Route::get('products/export/template', [ProductController::class, 'exportTemplate'])->name('products.export.template');
        Route::get('products/export/csv', [ProductController::class, 'exportCsv'])->name('products.export.csv');
        Route::post('products/import', [ProductController::class, 'importCsv'])->name('products.import');
        Route::post('products/bulk-update', [ProductController::class, 'bulkUpdate'])->name('products.bulk-update');
        Route::post('products/{product}/activate', [ProductController::class, 'activate'])->name('products.activate');
        Route::resource('products', ProductController::class)->except(['show'])->names('products');
        Route::get('stock-overview', [StockOverviewController::class, 'index'])->name('stock-overview.index');
        Route::get('stock-locations', [StockLocationController::class, 'index'])->name('stock-locations.index');
        Route::post('stock-locations', [StockLocationController::class, 'store'])->name('stock-locations.store');
        Route::put('stock-locations/{location}', [StockLocationController::class, 'update'])->name('stock-locations.update');
        Route::delete('stock-locations/{location}', [StockLocationController::class, 'destroy'])->name('stock-locations.destroy');
        Route::get('stock-transfers', [StockTransferController::class, 'index'])->name('stock-transfers.index');
        Route::get('stock-transfers/create', [StockTransferController::class, 'create'])->name('stock-transfers.create');
        Route::get('stock-transfers/available', [StockTransferController::class, 'available'])->name('stock-transfers.available');
        Route::post('stock-transfers', [StockTransferController::class, 'store'])->name('stock-transfers.store');
        Route::get('stock-transfers/{stockTransfer}', [StockTransferController::class, 'show'])->name('stock-transfers.show');
        Route::get('stock-adjustments/create', [StockAdjustmentController::class, 'create'])->name('stock-adjustments.create');
        Route::post('stock-adjustments', [StockAdjustmentController::class, 'store'])->name('stock-adjustments.store');
        Route::get('stock-movements', [StockMovementController::class, 'index'])->name('stock-movements.index');
        Route::get('stock-takes', [StockTakeController::class, 'index'])->name('stock-takes.index');
        Route::get('stock-takes/create', [StockTakeController::class, 'create'])->name('stock-takes.create');
        Route::post('stock-takes', [StockTakeController::class, 'store'])->name('stock-takes.store');
        Route::get('stock-takes/{stockTake}', [StockTakeController::class, 'show'])->name('stock-takes.show');
        Route::put('stock-takes/{stockTake}', [StockTakeController::class, 'update'])->name('stock-takes.update');
        Route::post('stock-takes/{stockTake}/start', [StockTakeController::class, 'start'])->name('stock-takes.start');
        Route::post('stock-takes/{stockTake}/review', [StockTakeController::class, 'review'])->name('stock-takes.review');
        Route::post('stock-takes/{stockTake}/approve', [StockTakeController::class, 'approve'])->name('stock-takes.approve');
        Route::post('stock-takes/{stockTake}/cancel', [StockTakeController::class, 'cancel'])->name('stock-takes.cancel');
        Route::resource('coupons', CouponController::class)->except(['show'])->names('coupons');
        Route::get('reviews', [AdminProductReviewController::class, 'index'])->name('reviews.index');
        Route::patch('reviews/{review}', [AdminProductReviewController::class, 'update'])->name('reviews.update');
        Route::delete('reviews/{review}', [AdminProductReviewController::class, 'destroy'])->name('reviews.destroy');
        Route::get('questions', [AdminProductQuestionController::class, 'index'])->name('questions.index');
        Route::patch('questions/{question}', [AdminProductQuestionController::class, 'update'])->name('questions.update');
        Route::delete('questions/{question}', [AdminProductQuestionController::class, 'destroy'])->name('questions.destroy');
        Route::get('reports', [ReportController::class, 'index'])->name('reports.index');
        Route::get('reports/cashier', [ReportController::class, 'cashier'])->name('reports.cashier');
        Route::get('reports/cashier/export', [ReportController::class, 'exportCashier'])->name('reports.cashier.export');
        Route::get('reports/stock-valuation', [ReportController::class, 'stockValuation'])->name('reports.stock-valuation');
        Route::get('reports/stock-valuation/export', [ReportController::class, 'exportStockValuation'])->name('reports.stock-valuation.export');
        Route::get('reports/online-sales-by-location', [ReportController::class, 'onlineSalesByLocation'])->name('reports.online-sales-by-location');
        Route::get('reports/export', [ReportController::class, 'export'])->name('reports.export');
        Route::get('reports/vendor-commissions/csv', [ReportController::class, 'exportVendorCommissionsCsv'])->name('reports.vendor-commissions.csv');
        Route::get('returns', [ReturnController::class, 'index'])->name('returns.index');
        Route::get('returns/create', [ReturnController::class, 'create'])->name('returns.create');
        Route::post('returns', [ReturnController::class, 'store'])->name('returns.store');
        Route::get('returns/{orderReturn}', [ReturnController::class, 'show'])->name('returns.show');
        Route::get('shifts', [CashierShiftController::class, 'index'])->name('shifts.index');
        Route::post('shifts', [CashierShiftController::class, 'store'])->name('shifts.store');
        Route::get('shifts/{shift}', [CashierShiftController::class, 'show'])->name('shifts.show');
        Route::post('shifts/{shift}/close', [CashierShiftController::class, 'close'])->name('shifts.close');
        Route::get('training', [TrainingController::class, 'index'])->name('training');
        Route::resource('orders', OrderController::class)->only(['index', 'show', 'update'])->names('orders');
        Route::post('orders/{order}/send-confirmation', [OrderController::class, 'sendConfirmation'])->name('orders.send-confirmation');
        Route::get('orders/{order}/print', [OrderController::class, 'print'])->name('orders.print');
        Route::get('orders/{order}/pdf', [OrderController::class, 'downloadPdf'])->name('orders.pdf');
        Route::post('orders/bulk-update', [OrderController::class, 'bulkUpdate'])->name('orders.bulk-update');
        Route::get('orders/export/csv', [OrderController::class, 'exportCsv'])->name('orders.export.csv');
        Route::resource('blog', BlogPostController::class)->names('blog');
        Route::resource('prices', PriceController::class)->names('price');
        Route::resource('gallery', GalleryController::class)->except(['show'])->names('gallery');
        Route::resource('news-events', NewsEventController::class)->except(['show'])->names('news-events');
        Route::resource('videos', VideoController::class)->except(['show'])->names('video');
        Route::resource('team', TeamMemberController::class)->except(['show'])->names('team');
        Route::get('backups', [BackupController::class, 'index'])->name('backups.index');
        Route::post('backups', [BackupController::class, 'store'])->name('backups.store');
        Route::post('backups/restore', [BackupController::class, 'restore'])->name('backups.restore');
        Route::get('backups/{file}', [BackupController::class, 'download'])->name('backups.download')->where('file', '[A-Za-z0-9._-]+');
        Route::delete('backups/{file}', [BackupController::class, 'destroy'])->name('backups.destroy')->where('file', '[A-Za-z0-9._-]+');
        Route::resource('users', UserController::class)->except(['show'])->names('users');
        Route::get('users/{user}/print-card', [UserController::class, 'printCard'])->name('users.print-card');
        Route::patch('users/{user}/role', [UserController::class, 'updateRole'])->name('users.role.update');
        Route::get('users/{user}/assign-roles', [UserController::class, 'assignRoles'])->name('users.assign-roles');
        Route::post('users/{user}/assign-roles', [UserController::class, 'updateRoles'])->name('users.update-roles');
        Route::post('users/{user}/reset-password', [UserController::class, 'resetPassword'])->name('users.reset-password');
        Route::resource('roles', RoleController::class)->except(['show'])->names('roles');
        Route::get('roles/{role}/assign-permissions', [RoleController::class, 'assignPermissions'])->name('roles.assign-permissions');
        Route::put('roles/{role}/assign-permissions', [RoleController::class, 'updatePermissions'])->name('roles.update-permissions');
        Route::resource('permissions', PermissionController::class)->except(['show'])->names('permissions');
        Route::post('permissions/sync-catalogue', [PermissionController::class, 'sync'])->name('permissions.sync');
        Route::post('permissions/prune-unused', [PermissionController::class, 'prune'])->name('permissions.prune');
        Route::resource('user-groups', UserGroupController::class)->except(['show'])->names('user-groups');
        Route::resource('quotes', QuoteRequestController::class)->only(['index', 'show', 'update', 'destroy'])->names('quotes');
        Route::get('quotes/{quote}/pdf', [QuoteRequestController::class, 'downloadPdf'])->name('quotes.pdf');

        Route::resource('quotations', QuotationController::class)->except(['show'])->names('quotations');
        Route::get('quotations/{quotation}/pdf', [QuotationController::class, 'generatePDF'])->name('quotations.pdf');
        Route::post('quotations/{quotation}/send-email', [QuotationController::class, 'sendEmail'])->name('quotations.send-email');
    });
});
