<?php

return [
    'routes' => [
        'admin.dashboard' => 'view_dashboard',
        'admin.reports.cashier' => 'view_cashier_performance',
        'admin.training' => 'create_sale',
        'admin.profile.edit' => null,
        'admin.profile.update' => null,
        'admin.stock-takes.approve' => 'approve_stocktakes',
        'admin.backups.restore' => 'restore_database',
        'admin.users.assign-roles' => 'assign_roles_to_users',
        'admin.users.update-roles' => 'assign_roles_to_users',
        'admin.users.create' => 'create_users',
        'admin.users.store' => 'create_users',
        'admin.users.edit' => 'edit_users',
        'admin.users.update' => 'edit_users',
        'admin.users.destroy' => 'delete_users',
        'admin.users.reset-password' => 'edit_users',
        'admin.users.role.update' => 'assign_roles_to_users',
        'admin.roles.assign-permissions' => 'assign_permissions_to_roles',
        'admin.roles.update-permissions' => 'assign_permissions_to_roles',
        'admin.roles.create' => 'create_roles',
        'admin.roles.store' => 'create_roles',
        'admin.roles.edit' => 'edit_roles',
        'admin.roles.update' => 'edit_roles',
        'admin.roles.destroy' => 'delete_roles',
        'admin.permissions.create' => 'create_permissions',
        'admin.permissions.store' => 'create_permissions',
        'admin.permissions.edit' => 'edit_permissions',
        'admin.permissions.update' => 'edit_permissions',
        'admin.permissions.destroy' => 'delete_permissions',
    ],
    'prefixes' => [
        'admin.pos.' => 'create_sale',
        'admin.orders.' => 'view_sales',
        'admin.returns.' => 'process_return',
        'admin.shifts.' => 'create_sale',
        'admin.products.' => 'manage_products',
        'admin.categories.' => 'manage_pos_categories',
        'admin.stock-takes.' => 'manage_stocktakes',
        'admin.coupons.' => 'manage_coupons',
        'admin.vendors.' => 'manage_vendors',
        'admin.vendor-payouts.' => 'manage_vendors',
        'admin.reports.' => 'view_pos_reports',
        'admin.blog.' => 'manage_blog',
        'admin.reviews.' => 'manage_reviews',
        'admin.questions.' => 'manage_reviews',
        'admin.backups.' => 'backup_database',
        'admin.users.' => 'view_users',
        'admin.roles.' => 'view_roles',
        'admin.permissions.' => 'view_permissions',
        'admin.settings.' => 'manage_system_settings',
        'admin.user-groups.' => 'manage_user_groups',
    ],
];
