<?php

return [
    'blog_categories' => [
        'ICT Trends & Innovations',
        'Digital Transformation',
        'Cloud Computing',
        'Cybersecurity',
        'Artificial Intelligence (AI)',
        'Data Analytics & Business Intelligence',
        'ICT for SMEs',
        'Government & Public Sector Systems',
        'Enterprise Solutions',
        'ERP Systems (like Microsoft Dynamics)',
        'Workflow Automation',
        'Tutorials & How-To Guides',
        'Case Studies',
        'System Implementation Stories',
        'Best Practices',
        'Troubleshooting & Support',
        'eCitizen & Government Systems',
        'AGPO & Tender Systems',
        'Digital Services in Kenya',
        'Company News',
        'Project Highlights',
        'Product Updates',
    ],

    'service_categories' => [
        'Custom Software Development',
        'Web Application Development',
        'Mobile App Development',
        'ERP & CRM Solutions',
        'Network Setup & Configuration',
        'Server Installation & Management',
        'Cloud Services (AWS, Azure, etc.)',
        'Data Backup & Recovery',
        'Security Audits',
        'Penetration Testing',
        'Data Protection Solutions',
        'User Access Control Systems',
        'ICT Consultancy',
        'Digital Transformation Strategy',
        'System Analysis & Design',
        'IT Project Management',
        'System Maintenance',
        'Technical Support',
        'Helpdesk Services',
        'System Upgrades',
        'Staff ICT Training',
        'System User Training',
        'Cybersecurity Awareness',
    ],

    'pricing_plan_templates' => [
        'basic' => [
            'label' => 'Basic Plan (Starter)',
            'title' => 'BASIC PLAN',
            'subtitle' => 'Ideal for startups & small businesses',
            'description' => 'Starter package for small organizations that need a reliable online presence quickly.',
            'amount_hint' => 'KES 15,000 - 50,000',
            'features' => [
                'Basic consultation',
                'Website / small system setup',
                'Email support',
                '1-2 revisions',
            ],
        ],
        'standard' => [
            'label' => 'Standard Plan (Most Popular)',
            'title' => 'STANDARD PLAN',
            'subtitle' => 'Most Popular ⭐',
            'description' => 'Balanced package for organizations that need full system delivery with faster support.',
            'amount_hint' => 'KES 60,000 - 150,000',
            'features' => [
                'Full system development',
                'Custom features',
                'Training included',
                'Priority support',
                '1-month maintenance',
            ],
        ],
        'premium' => [
            'label' => 'Premium Plan (Enterprise)',
            'title' => 'PREMIUM PLAN',
            'subtitle' => 'Enterprise',
            'description' => 'Enterprise-grade package for high-scale systems, integrations, and dedicated delivery.',
            'amount_hint' => 'KES 200,000+',
            'features' => [
                'Advanced system development',
                'Integration (M-Pesa, APIs)',
                'Dedicated support',
                'On-site training',
                '3-6 months maintenance',
            ],
        ],
        'custom' => [
            'label' => 'Custom Plan',
            'title' => 'CUSTOM PLAN',
            'subtitle' => 'Tailored for your needs',
            'description' => 'Tailored consultancy package based on project requirements with flexible pricing.',
            'amount_hint' => 'Request a Quote',
            'features' => [
                'Tailored solution scope',
                'Flexible and requirement-based pricing',
                'Custom implementation roadmap',
            ],
        ],
    ],
];
